---
erlang/otp_src_R14B01.tar.gz:
  object_id: 30db9c17-bdb6-4d54-8b7e-481b14051de5
  sha: !binary |-
    ZjBlMDUyOWVkNzM1ODdjMmM0YWFlYjNmM2EwMTU1NWJkNmNmZTA1Yw==
  size: 64846537
memcached/libevent-2.0.19-stable.tar.gz:
  object_id: 4efed450-345b-4033-ab75-f60aa14215ee
  sha: !binary |-
    MjhjMTA5MTkwMzQ1Y2U1NDY5YWRkOGNmM2Y0NWM1ZGQ1N2ZlMmE4NQ==
  size: 842961
memcached/memcached-1.4.13.tar.gz:
  object_id: f61b5dd1-a7f5-4d3e-84fd-fa9cc9ac4966
  sha: !binary |-
    ZDlhNDhkMjIyZGU1M2EyNjAzZmJhYjYxNTZkNDhkMGU4OTM2ZWU5Mg==
  size: 320751
node/node-v0.4.12.tar.gz:
  object_id: 2839baf1-9f12-4569-9198-07c831b99550
  sha: !binary |-
    MWM2ZTM0YjkwYWQ2Yjk4OTY1OGVlODVlMGQwY2IxNjc5N2IxNjQ2MA==
  size: 12421469
ruby/rubygems-1.8.24.tgz:
  object_id: 989fc0dc-0d6c-4c7b-bff9-787d30d77e96
  sha: !binary |-
    MzBmMjcwNDdlNzRmNzk0MzExNzczNmEwZDNlMjI0OTk0ZmVlMDkwNQ==
  size: 380101
ruby/ruby-1.9.2-p180.tar.gz:
  object_id: 4c79d898-9f49-4e61-912e-7e91e344bfb1
  sha: !binary |-
    NmE0ODJiYzA3MjM5YjM3YmNhZGY2OGRkYTYzYzY1ZDIwZGMxOWViZQ==
  size: 11158935
ruby/bundler-1.2.1.gem:
  object_id: 159c8f20-174f-41e7-8c2f-d63f41f65475
  sha: !binary |-
    MGNiZTZhZDdhNDFmMDY0ZDZjMTFjMTA1ODQ2NWZmZmIxYmQ1ODA2OQ==
  size: 226816
ruby/ruby-1.9.3-p392.tar.gz:
  object_id: c1237f02-fb79-4cfb-9fba-e5acf9090f28
  sha: !binary |-
    ZWM3NWZjYmQzYjZiNDZjZTZlYzk5N2VlNGM4NjE0NWI0YWJkNTc0OA==
  size: 12557294
golang/go1.1.1.src.tar.gz:
  object_id: 9d13e73d-312c-40bd-aed0-6e6d7da3c34e
  sha: !binary |-
    ZjM2NWFlZDgxODNlNDg3YTQ4YTY2YWNlN2JmMzZlNTk3NGRmZmJiMw==
  size: 9045336
rabbitmq/rabbitmq-server-with-plugins-generic-unix-3.0.4.tar.gz:
  object_id: e0c0cda2-0c7d-4879-8bd0-7ec50f5fabee
  sha: !binary |-
    NzBlYTY5MTIyNTEwNTZmNDlkN2JmMmE5NGYxZWE1ODUyZDA1MThjYQ==
  size: 3570257
rabbitmq/rabbitmq-server-with-plugins-generic-unix-2.4.1.tar.gz:
  object_id: 44d6ed5a-9f79-4206-8ae5-b94df3c8efa7
  sha: !binary |-
    ZGZkZmNmOTg4YTc4MGFmMDM0YzE1NjhjYWU5NmU2YTg0ZTBjMzY2OA==
  size: 1780598
rabbitmq/rabbitmq-server-with-plugins-generic-unix-2.8.7.tar.gz:
  object_id: 510becff-a836-4b00-a1f2-fc93ee02301e
  sha: !binary |-
    MjNkYjRjMGZiOGE0M2EwMTMxZjhlOTA5YzI4MjFhYWY4NWVhNDEwYg==
  size: 2894762
libyaml/yaml-0.1.4.tgz:
  object_id: a197ef94-5eb7-4ac7-b3a2-2ddb60d8ecad
  sha: !binary |-
    ZTBlNWUwOTE5MmFiMTBhNjA3ZTNkYTI5NzBkYjQ5MjExOGY1NjBmMg==
  size: 471759
mongodb/mongodb-linux-i686-2.0.9.tgz:
  object_id: a65715c5-797b-49ce-89e9-9827d7baad31
  sha: !binary |-
    M2QyNGUwZjhhNTU1NDc0N2Q0YTZlZDFlMTkzYTQ4OWQyYzEyMzA3NA==
  size: 38415939
mongodb/mongodb-linux-x86_64-2.2.4.tgz:
  object_id: ec81cadc-805a-4f59-8816-f6c5002cb774
  sha: !binary |-
    YzJlZjMwYTdjNzAzOWI0ZDQ5OWU5OTA0NTRiMDBhMjAzMmU2ZjE5Zg==
  size: 56410012
mongodb/mongodb-linux-x86_64-1.8.5.tgz:
  object_id: e1df91b1-d114-4f79-a4dc-d4a94b755e33
  sha: !binary |-
    MjM1NjA1ZjMwNmI2NjU4NGQyYWEwMGI2MWQ0NWI0NjA1Zjg3ODY3ZQ==
  size: 28156593
mongodb/mongodb-linux-i686-1.8.5.tgz:
  object_id: 5b419039-e76f-48ca-ade8-59067931b065
  sha: !binary |-
    Zjc1ZDJmZDdhNGUwYTcxMTZlYTYxMmJiNjJiNzEwYTFiYTBmYTJiMg==
  size: 27749757
mongodb/mongodb-linux-x86_64-2.0.9.tgz:
  object_id: 4ec710e1-4384-4b2b-b8bb-94c99d49df94
  sha: !binary |-
    NDE3NmQzYmE1ODMyMzVmZGRkNDAzZWIzMzVmN2I3MzUzNjA0ZmNlOA==
  size: 38649815
nginx/pcre-8.12.tar.gz:
  object_id: 082b074c-80b4-4bd3-a8ac-a5d632e840d6
  sha: !binary |-
    YjNhYjYwNjg2NDYwNmM5Zjk4MDA0NTY1MzU1NGJmNGExMmNhZGRlMg==
  size: 1316863
nginx/devel-kit-v0.2.17rc2.tar.gz:
  object_id: 3a2ae0cd-aab8-4d06-9823-dd145732ba89
  sha: !binary |-
    N2VhZGZlNTNkNjc0OTcyYzBmN2YyN2Q3YjI2ZWZmOTU4MjliYzBiMg==
  size: 64964
nginx/lua-openssl-0.1.1.tar.gz:
  object_id: 9cf447e0-9e2f-4601-abd1-453e983f295c
  sha: !binary |-
    MjdmMzhiM2Y3ZDQ0ZjU5NjkwZWQwODFmODkyODkxYTM1YTVlYmZhYQ==
  size: 69253
nginx/nginx-lua.v0.3.1rc24.tar.gz:
  object_id: c09665bd-db76-4bbd-bbcf-45496127ba99
  sha: !binary |-
    ZjA2ZTM5MGNjODFmODJiMDVhMDY0NTFiZjdiMjg3YjdkNGZiMTY0MA==
  size: 207185
nginx/nginx_upload_module-2.2.0.tar.gz:
  object_id: 1ab4577f-94b1-4fef-8aef-50f80c78a60f
  sha: !binary |-
    OTNkNmU4M2U2MTNhMGNlMmVkMDU3YTQzNGIzNDRmYTFiNjYwOWI0Nw==
  size: 25796
nginx/lua-5.1.4.tar.gz:
  object_id: dedf8e44-44f1-47a5-bda1-d828ae3007e6
  sha: !binary |-
    MmIxMWM4ZTYwMzA2ZWZiN2YwNzM0Yjc0NzU4OGY1Nzk5NTQ5M2RiNw==
  size: 216679
nginx/headers-more-v0.15rc1.tgz:
  object_id: 6ac96f7d-6b13-4a13-8572-2d256f66faf2
  sha: !binary |-
    YmE3YmY3NTdiZTgwMDRkOWRiZmZiZTU4MzM5NjYyMGNmY2JlZDc4OA==
  size: 25490
nginx/nginx-0.8.54.tar.gz:
  object_id: 899b003b-d1f5-4f85-8ff3-535f6bb4d568
  sha: !binary |-
    NGQ2M2MzNWI4OTc0ZGJhNDJjYzYyZGQ1MDQ2YWU4OWRmMzUyOGUzNA==
  size: 650001
nginx/lua-cjson-1.0.3.tar.gz:
  object_id: 0f356801-f0f4-48ef-90d2-df01e6746de5
  sha: !binary |-
    NzMzNTk2MWZmNjYxOWE3ZWFlODI0ZThjZjk0MzIxMDBjYTM3NzQ3Ng==
  size: 31780
nginx/lbase64.tar.gz:
  object_id: 101fd09f-478a-436c-8156-696840919a13
  sha: !binary |-
    NTY5MjYxOWRhZTc4MGRiZGY5ZWRjOTk0ZjlkY2Q3ZGNlN2IyNDY0Ng==
  size: 2503
postgresql/postgresql-9.0.13-x86_64.tar.gz:
  object_id: f74c1e68-a005-4fe8-a1a5-4868ff7df988
  sha: !binary |-
    MDRjOWM5NDE2MTU1MjQwOGVhYTY1YjBhM2ZiYTMxMmFlYzA4YWExYQ==
  size: 24861255
postgresql/postgresql-initdb-9.0-x86_64.tar.gz:
  object_id: 33484eeb-7f43-435f-af64-ef6ee39aa635
  sha: !binary |-
    MTgxOTAwYzYzNDZmNzE4Y2NkN2NmYmI4ODEzZTdjMDBmNzYwYmM1NQ==
  size: 3467921
postgres/postgres-9.0.3-1.amd64.tar.gz:
  object_id: 100076ea-340f-43ce-84d6-22338972998a
  sha: !binary |-
    ZTQ3ZWU5Yzg0MWVjZGU0ZGYxMjFmNDRkZjI4MmFlYjNjNTBhNDhkMg==
  size: 16203511
postgres/postgres-9.0.3-1.i386.tar.gz:
  object_id: 7ef005ea-09ed-47fd-aa7c-589239c69e78
  sha: !binary |-
    YjJiZGUzMWU3MjBlYjIxOWJmZGM5ZjFiNzg0Zjk4NWVjY2EyY2JmYg==
  size: 15111387
mysql/mysql-initdb-5.1.62-rel13.3-435-Linux-x86_64.tar.gz:
  object_id: e8b54d01-bd4a-4399-84b0-a0203675adc2
  sha: !binary |-
    ODEyMmJjZDk2YzNmYTI1MWNlNmE0MzE3NTcwZDAxYjRiZjJiODQyMA==
  size: 53356
mysql/client-5.1.62-rel13.3-435-Linux-x86_64.tar.gz:
  object_id: 66e7c4cf-231f-4535-ba64-b9d7789f59b0
  sha: !binary |-
    NmU1YTE3MTk1ODMxNjg4YTVmMTRmMjBhYTVkOWNkNWQ1ZjQxNjRkYg==
  size: 4105211
mysql/client-5.5.29-rel29.4-401.Linux.x86_64.tar.gz:
  object_id: cc83ca76-abbc-4785-832e-41d85f66b4a4
  sha: !binary |-
    OGRhZDViMmQ5ZmVlN2IwYTk4ZTQxOTk0OWM2ZjdkOTRjMzk0NDNmMg==
  size: 4564276
mysql/server-5.1.62-rel13.3-435-Linux-x86_64.tar.gz:
  object_id: bd806261-6c19-4f56-92c9-066a8536eced
  sha: !binary |-
    MmJmZDU3NTU0NWZlNzg3MjljNTZiYjgzMmFhNjlkOGQ5ZmM4NjMwZA==
  size: 34179263
sqlite/sqlite-autoconf-3070500.tar.gz:
  object_id: 36d0442d-afb4-405f-9f6d-9974d80722bf
  sha: !binary |-
    NGUxMzM4NDk3YjhkYTUwYjg0MzA3MTkxYmIzNDE4ZTllYzU3MTVkNw==
  size: 1551070
redis/redis-2.2.15.tar.gz:
  object_id: 7d40bc1e-8e6b-44e1-9562-9dd98ca0b893
  sha: !binary |-
    YWE2NzU4NTkwMzYzNTU2ZTczZjhkMzZiZGZjY2I0MjkwMTFkYTMzMQ==
  size: 456185
redis/redis-2.6.2.tar.gz:
  object_id: eed36d97-7782-47e6-bc97-f2cc5659c982
  sha: !binary |-
    OTNlNjMyY2U4OGRlMDdhOTg0NWFhNWJjYWI2N2JkYzE2YTdiNTc0YQ==
  size: 1000600
redis/redis-2.4.17.tar.gz:
  object_id: eba416c5-90a7-4d62-8995-aaf137efa05e
  sha: !binary |-
    M2Q1NDA1MzFiM2Q3MTAzYTUxMWQyOTY2MWMyYWU2NjZkYWM2MDUyMg==
  size: 656155