---
sqlite/sqlite-autoconf-3070500.tar.gz:
  object_id: 618efa31-b7c3-4dd9-9674-369dee2a6c73
  sha: !binary |-
    NGUxMzM4NDk3YjhkYTUwYjg0MzA3MTkxYmIzNDE4ZTllYzU3MTVkNw==
  size: 1551070
memcached/libevent-2.0.19-stable.tar.gz:
  object_id: f91b81e9-50a2-4666-9f08-92ed7988d4a6
  sha: !binary |-
    MjhjMTA5MTkwMzQ1Y2U1NDY5YWRkOGNmM2Y0NWM1ZGQ1N2ZlMmE4NQ==
  size: 842961
memcached/memcached-1.4.13.tar.gz:
  object_id: 7d2229a8-76ca-4a6e-bafc-6bf2fd2a02ac
  sha: !binary |-
    ZDlhNDhkMjIyZGU1M2EyNjAzZmJhYjYxNTZkNDhkMGU4OTM2ZWU5Mg==
  size: 320751
ruby/rubygems-1.7.2.tgz:
  object_id: 946b8af4-62ce-476e-83f7-83c821c38c04
  sha: !binary |-
    ZDg3OGFlNTJmNDBlYjcxZTU5NzA4YWZjNTczMDMxNzJmMDMyN2ZhZA==
  size: 245606
ruby/bundler-1.2.1.gem:
  object_id: 0571d9dc-9649-47d1-a892-8d9efcb38f01
  sha: !binary |-
    MGNiZTZhZDdhNDFmMDY0ZDZjMTFjMTA1ODQ2NWZmZmIxYmQ1ODA2OQ==
  size: 226816
ruby/rake-0.8.7.gem:
  object_id: 816dbeff-a6d8-4644-8a8a-3578f0b2ce33
  sha: !binary |-
    OTFkYWFkMDc5ZDQwNGI2OGE3ZGQxNzk3MTZiOWZkZDBjMTk1MTQ0Yw==
  size: 104960
ruby/ruby-1.9.2-p180.tar.gz:
  object_id: a439cf0d-1f6c-4ac8-8709-23d6170b54d6
  sha: !binary |-
    NmE0ODJiYzA3MjM5YjM3YmNhZGY2OGRkYTYzYzY1ZDIwZGMxOWViZQ==
  size: 11158935
ruby/rubygems-1.8.24.tgz:
  object_id: b89a02b5-0d5b-454e-bd5c-a322fd86ca47
  sha: !binary |-
    MzBmMjcwNDdlNzRmNzk0MzExNzczNmEwZDNlMjI0OTk0ZmVlMDkwNQ==
  size: 380101
ruby/ruby-1.9.3-p392.tar.gz:
  object_id: 485d6468-6587-4cf2-9737-f1affaa07974
  sha: !binary |-
    ZWM3NWZjYmQzYjZiNDZjZTZlYzk5N2VlNGM4NjE0NWI0YWJkNTc0OA==
  size: 12557294
libyaml/yaml-0.1.4.tgz:
  object_id: d3045ea9-b279-4f34-9455-898de29ee2c3
  sha: !binary |-
    ZTBlNWUwOTE5MmFiMTBhNjA3ZTNkYTI5NzBkYjQ5MjExOGY1NjBmMg==
  size: 471759
node/node-v0.6.8.tar.gz:
  object_id: 7b580327-b416-43ff-9d00-d983543aca65
  sha: !binary |-
    YzNmNzU1YjVkZmQwZGUzZjMwNmQwNjU3M2ZhOTQzM2Q4NDU2MjNkZA==
  size: 10488841
node/node-v0.4.12.tar.gz:
  object_id: 9083d445-8759-47b2-90c7-87ebcd00d1d8
  sha: !binary |-
    MWM2ZTM0YjkwYWQ2Yjk4OTY1OGVlODVlMGQwY2IxNjc5N2IxNjQ2MA==
  size: 12421469
node/npm-v1.0.106.tgz:
  object_id: 9ffc7142-5794-4433-bec0-519d1f217427
  sha: !binary |-
    ZWYxODMwYjY4YTE1MzdhNjA2ZGFlM2JkZWU3MWZkMTE1M2Q3ZTcxZQ==
  size: 1187840
node/node-v0.8.2.tar.gz:
  object_id: 8a5f97e3-e266-4b14-87a4-c46eaff353d3
  sha: !binary |-
    MGU3NDNkMjFiNDg3MTUxZTY3OTUwZjA5MTk4ZGVmMDU4ZGIxOWExZQ==
  size: 11727164
git/git-1.7.11.2.tar.gz:
  object_id: 6ae717a8-b207-4340-8674-a869896f2b62
  sha: !binary |-
    ZjY3YjRmNmMwMjc3MjUwNDExYzY4NzJhZTdiOGE4NzJhZTExZDMxMw==
  size: 4015780
rootfs/lucid64.tar.gz:
  object_id: 6fa09ac2-5463-40c0-962b-8228621d7b11
  sha: !binary |-
    YjI2MzNiMmFiNDk2NGY5MTQwMmJiMmQ4ODlmMmYxMjQ0OWE4YjgyOA==
  size: 199489185
