---
final_name: cf-services-contrib
blobstore:
  provider: s3
  options:
    bucket_name: cf-contrib
    access_key_id: AKIAIKXFR4244ZYGZ52A
    secret_access_key: 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
